#!/bin/bash
# convert wal colors to hyprland
source ~/.cache/wal/colors.sh

cat > ~/.cache/wal/hyprland-colors.conf <<EOL
# Generated by Pywal
general {
    background = $background
    foreground = $foreground
}

window {
    border_active = $color1
    border_inactive = $color0
}
EOL

