#################
### AUTOSTART ###
#################

#exec-once = eww open eww-bar0
exec-once = /usr/libexec/polkit-mate-authentication-agent-1
exec-once = swaync & 
exec-once = hyperidle & 
exec-once = hyprpaper & 
exec-once = blueman-applet & 
exec-once = onedrive -s & 
exec-once = ~/.config/hypr/scripts/randomWallpaper.sh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = /usr/libexec/polkit-kde-authentication-agent-1
exec-once = eww open eww-bar0
