


# https://wiki.hypr.land/Configuring/Variables/#decoration
source = ~/.cache/wal/colors-hyprland.conf
decoration {
    active_opacity = 1
    rounding = 1

    blur {
        size = 3
        passes = 2 # more passes = more resource intensive.
        xray = true
		new_optimizations = true
    }

    shadow {
        enabled = false
    }

}
