##############################
### WINDOWS AND WORKSPACES ###
##############################



# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

workspace = 1, 
workspace = 2, on-created-empty: firefox
workspace = 3,
workspace = 4,
workspace = 5, 
workspace = 6, 



# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$



