wallpaper {
    monitor = DP-1
    path =  /home/lilo/.config/hypr/backgrounds/DarthVaderWallpaper.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path =  /home/lilo/.config/hypr/backgrounds/DarthVaderWallpaper.jpg
    fit_mode = cover
}
